{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"8.Functions_and_ErrorHandling.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"46CX2a6-BxLA"},"source":["# Anonymous functions (lambda)\n","\n","A lambda function is a small anonymous function. It can take any number of arguments, but can only have one expression. The syntax is as follows: \n","\n","`lambda arguments : expression`"]},{"cell_type":"code","metadata":{"id":"7ba9E9D1BxOq"},"source":["# A lambda function that adds 10 to the number passed\n","#  in as an argument, and print the result\n","x = lambda a: a + 10\n","def xx(a): return a + 10\n","\n","print(x(5))\n","print(xx(5))"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Oz9ps-ASCxTj"},"source":["#A lambda function that multiplies argument a with argument b\n","#  and print the result\n","x = lambda a, b: a * b\n","print(x(5, 6))"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"7eMbg-lZCxXs"},"source":["The power of lambda is better shown when you use them as an anonymous function inside another function.\n","\n","Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number."]},{"cell_type":"code","metadata":{"id":"OU8ti4P6Cxco"},"source":["def myfunc(n):\n","  return lambda a : a ** n\n","\n","mydoubler = myfunc(n=2)\n","print(mydoubler(a=11))"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"ZefU8XhpCxg1"},"source":["Or you want to sort a dictionary"]},{"cell_type":"code","metadata":{"id":"JNv2eHz1CxlZ"},"source":["some_dict = {'A':1, 'B': 200, 'C':50}"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LeDTncluDCNI"},"source":["sorted(some_dict)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"mhmfQfVbDHoI"},"source":["help(sorted)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"uq9JumpwB0cm"},"source":["sorted(some_dict.items())"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"PPAmiNyRCxpL"},"source":["# sorted(some_dict.items())\n","sorted(some_dict.items(), key=lambda x: x[1], reverse=True)\n","\n","# def my_func(x): return x[1]\n","# sorted(some_dict.items(), key=my_func, reverse=True)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"LEZ869d8Cxtt"},"source":["# sorting a dict by values\n","sorted_dict = {k: v for k, v in sorted(some_dict.items(), \n","                                       key=lambda x: x[1])}\n","print(sorted_dict)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"8vjjF0hACxxQ"},"source":["# sorting a dict by values\n","sorted_dict = {k: v for k, v in sorted(some_dict.items(), \n","                                       key=lambda x: x[1],\n","                                       reverse=True)}\n","print(sorted_dict)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"dqKDpbfrC8zn"},"source":["my_list = [('Armen', 'Sargsyan', 45),\n","           ('Arman', 'Yesiminchyan', 15),\n","           ('Gor', 'Argsyan', 65),\n","           ('Davit', 'Sargsyan', 25)\n","           ]\n","\n","sorted(my_list, key=lambda a:a[-1], reverse=True)"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"FFRkoRQnC832"},"source":["# Recursive Functions\n","\n","In Python, we know that a function can call other functions. It is even possible for the function to call itself. These types of construct are termed as recursive functions.\n","\n","<img src=\"https://cdn.programiz.com/sites/tutorial2program/files/python-recursion-function.png\" alt=\"Drawing\" width=500/>\n"]},{"cell_type":"code","metadata":{"id":"LnO0v80vC88L"},"source":["def factorial(x):\n","    \"\"\"This is a recursive function\n","    to find the factorial of a given integer\n","    \"\"\"\n","\n","    if x == 1:\n","        return 1\n","    return x * factorial(x-1)\n","\n","\n","num = 5\n","print(\"The factorial of\", num, \"is\", factorial(num))"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"EFrKgz-RC8_o"},"source":["```\n","factorial(3)          # 1st call with 3\n","\n","3 * factorial(2)      # 2nd call with 2\n","\n","3 * 2 * factorial(1)  # 3rd call with 1\n","\n","3 * 2 * 1             # return from 3rd call as number=1\n","\n","3 * 2                 # return from 2nd call\n","\n","6                     # return from 1st call\n","```"]},{"cell_type":"markdown","metadata":{"id":"okh4wYdtqmua"},"source":["<img src=\"https://cdn.programiz.com/sites/tutorial2program/files/python-factorial-function.png\" alt=\"Drawing\" width=500/>"]},{"cell_type":"markdown","metadata":{"id":"6UMqmqMPqmzX"},"source":["## Maintaining State\n","\n","When dealing with recursive functions,  each recursive call has its own execution context, so to maintain state during recursion you have to either:\n","\n","* Thread the state through each recursive call so that the current state is part of the current call's execution context\n","* Keep the state in global scope\n","\n","Let's calculate 1 + 2 + 3 ⋅⋅⋅⋅ + 10 using recursion. The state that we have to maintain is (current number we are adding, accumulated sum till now)"]},{"cell_type":"code","metadata":{"id":"7LSa9ARxqm4F"},"source":["def sum_recursive(current_number, accumulated_sum):\n","    # Base case\n","    # Return the final state\n","    if current_number == 11:\n","        return accumulated_sum\n","\n","    # Recursive case\n","    # Thread the state through the recursive call\n","    else:\n","        return sum_recursive(current_number + 1,\n","                             accumulated_sum + current_number)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"znDS1ET2qm8F"},"source":["sum_recursive(current_number=1, accumulated_sum=0)"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"tCxBgtweqnAO"},"source":["![](https://robocrop.realpython.net/?url=https%3A//files.realpython.com/media/state_3.3e8a68c4fde5.png&w=646&sig=fb3a998a03c66aac067a7bb0a6bdd14f36773680)"]},{"cell_type":"code","metadata":{"id":"xRtwFoYnLNHX","colab":{"base_uri":"https://localhost:8080/","height":354},"executionInfo":{"status":"error","timestamp":1597412055772,"user_tz":-240,"elapsed":4193,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"7d355c4e-7fc4-4f90-dd5a-d70f49a28ef0"},"source":["def my_func(x):\n","  my_func(x+1)\n","\n","print(my_func(3))"],"execution_count":null,"outputs":[{"output_type":"error","ename":"RecursionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRecursionError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-31-fb0a5c4a04ac>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m   \u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-31-fb0a5c4a04ac>\u001b[0m in \u001b[0;36mmy_func\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m   \u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","... last 1 frames repeated, from the frame below ...\n","\u001b[0;32m<ipython-input-31-fb0a5c4a04ac>\u001b[0m in \u001b[0;36mmy_func\u001b[0;34m(x)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m   \u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmy_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRecursionError\u001b[0m: maximum recursion depth exceeded"]}]},{"cell_type":"markdown","metadata":{"id":"Xqce87MKqnEQ"},"source":["## Advantages of Recursion\n","\n","* Recursive functions make the code look clean and elegant.\n","* A complex task can be broken down into simpler sub-problems using recursion.\n","* Sequence generation is easier with recursion than using some nested iteration.\n","\n","## Disadvantages of Recursion\n","\n","* Sometimes the logic behind recursion is hard to follow through.\n","* Recursive calls are expensive (inefficient) as they take up a lot of memory and time.\n","* Recursive functions are hard to debug."]},{"cell_type":"markdown","metadata":{"id":"owqpm1xYqnI1"},"source":["Remember Fibonacci numbers\n","\n","1, 1, 2, 3, 5, 8, 13, 21 ... \n","\n","$f_1=f_2=1$\n","\n","$f_n=f_{n-1}+f_{n-2}, \\, n=3,...$\n"]},{"cell_type":"code","metadata":{"id":"8xN34YHsqnMg"},"source":["def fibonacci(n):\n","  if n <= 2:\n","    return 1\n","  return fibonacci(n-1) + fibonacci(n-2)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"llYB6KbRqnQ5"},"source":["def fibonacci_with_loop(n):\n","  a = 1\n","  b = 0\n","  for i in range(n):\n","    c = a + b\n","    a, b = b, c\n","  return c"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"7cuuPMGZqnVG"},"source":["from math import sqrt\n","\n","def fibonacci_analytical(n):\n","    return ((1+sqrt(5))**n - (1-sqrt(5))**n) / (2**n*sqrt(5))"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"xmV__bGVqnaV","colab":{"base_uri":"https://localhost:8080/","height":67},"executionInfo":{"status":"ok","timestamp":1597411358872,"user_tz":-240,"elapsed":22427,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"e78d42ae-e327-4c1f-b2a2-2b8115edd67c"},"source":["import time\n","\n","start = time.time()\n","fibonacci(40)\n","end = time.time()\n","print('Recursive version:',round(end - start, 2))\n","\n","start = time.time()\n","fibonacci_with_loop(40)\n","end = time.time()\n","print(f'Loop version: {end - start:.5f}')\n","\n","start = time.time()\n","fibonacci_analytical(40)\n","end = time.time()\n","print('Analytical version: {:.5f}'.format(end - start))"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Recursive version: 21.33\n","Loop version: 0.00004\n","Analytical version: 0.00005\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"WSVqFagPqndZ","colab":{"base_uri":"https://localhost:8080/","height":67},"executionInfo":{"status":"ok","timestamp":1597411607313,"user_tz":-240,"elapsed":1026,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"d93d5e49-4c5a-4e6f-fe11-da34671783e0"},"source":["%%time\n","fibonacci_with_loop(100)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["CPU times: user 13 µs, sys: 0 ns, total: 13 µs\n","Wall time: 16 µs\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["354224848179261915075"]},"metadata":{"tags":[]},"execution_count":25}]},{"cell_type":"code","metadata":{"id":"UbMOVvXbqnhp","colab":{"base_uri":"https://localhost:8080/","height":67},"executionInfo":{"status":"ok","timestamp":1597411547800,"user_tz":-240,"elapsed":1090,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"b082458e-1167-4304-97e3-e64b428e62f3"},"source":["%%time\n","fibonacci_analytical(100)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["CPU times: user 15 µs, sys: 0 ns, total: 15 µs\n","Wall time: 28.6 µs\n"],"name":"stdout"},{"output_type":"execute_result","data":{"text/plain":["3.542248481792631e+20"]},"metadata":{"tags":[]},"execution_count":23}]},{"cell_type":"code","metadata":{"id":"yzaVmXXIqnl_","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597411581765,"user_tz":-240,"elapsed":3542,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"0995544d-741a-45b9-a6e2-5b840636e2f3"},"source":["%%timeit \n","fibonacci_with_loop(100)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["100000 loops, best of 3: 5.95 µs per loop\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Eej5mp0PqnqL","colab":{"base_uri":"https://localhost:8080/","height":50},"executionInfo":{"status":"ok","timestamp":1597411660274,"user_tz":-240,"elapsed":5041,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"4bf3ad46-c64d-42eb-d7da-6a79cd89c740"},"source":["%%timeit\n","fibonacci_analytical(100)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["The slowest run took 11.46 times longer than the fastest. This could mean that an intermediate result is being cached.\n","1000000 loops, best of 3: 967 ns per loop\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"0DoD9jNBqnu8"},"source":["The [list](https://ipython.readthedocs.io/en/stable/interactive/magics.html) of magic commands in Jupyter Notebook."]},{"cell_type":"markdown","metadata":{"id":"G13RNbOwqnzB"},"source":["# Error Handling\n","\n","A Python program finishes as soon as it encounters an error. In Python, an error can be \n","* a syntax error \n","* an exception. \n"]},{"cell_type":"markdown","metadata":{"id":"rPk002AWqn3F"},"source":["# Exceptions vs Syntax Errors\n","\n","Syntax errors occur when the parser detects an incorrect statement. \n"]},{"cell_type":"code","metadata":{"id":"1mH-MP_uqn7Y","colab":{"base_uri":"https://localhost:8080/","height":128},"executionInfo":{"status":"error","timestamp":1597411792307,"user_tz":-240,"elapsed":1357,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"8187b02b-a7f9-45f8-e1c4-5064503c4dc2"},"source":["print('one'))"],"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-27-4aba51e36416>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print('one'))\u001b[0m\n\u001b[0m                ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"code","metadata":{"id":"PTM2Er67qoAS","colab":{"base_uri":"https://localhost:8080/","height":128},"executionInfo":{"status":"error","timestamp":1597411834775,"user_tz":-240,"elapsed":1098,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"21920be2-bb91-4fa9-da18-cd741c158c00"},"source":["for i in range(4)\n","  print(i)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-28-efe451265359>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    for i in range(4)\u001b[0m\n\u001b[0m                     ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"markdown","metadata":{"id":"ro_jsH-IqoEY"},"source":["The arrow indicates where the parser ran into the **syntax error**."]},{"cell_type":"code","metadata":{"id":"pQZTZx1lqoIn","colab":{"base_uri":"https://localhost:8080/","height":162},"executionInfo":{"status":"error","timestamp":1597411872362,"user_tz":-240,"elapsed":1084,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"544e90a9-6774-43e7-fd47-df35615b99f3"},"source":["print(5 / 0)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-29-34630cd80504>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","metadata":{"id":"ZdMd9j9MqoNF"},"source":["This time, you ran into an **exception error**. This type of error occurs whenever syntactically correct Python code results in an error. The last line of the message indicated what type of exception error you ran into.\n","\n","Instead of showing the message exception error, Python details what type of exception error was encountered. In this case, it was a ZeroDivisionError. Python comes with various [built-in exceptions](https://docs.python.org/3/library/exceptions.html) as well as the possibility to create self-defined exceptions."]},{"cell_type":"markdown","metadata":{"id":"Nxal_F5TqoRN"},"source":["# Raising an Exception\n","\n","We can use `raise` to throw an exception if a condition occurs. The statement can be complemented with a custom exception.\n","\n","<img src=\"https://files.realpython.com/media/raise.3931e8819e08.png\" alt=\"Drawing\" width=600/>\n"]},{"cell_type":"code","metadata":{"id":"6dZA06UKqoVa"},"source":["x = 10\n","if x > 5:\n","  raise Exception(f'x should not exceed 5. The value of x was: {x}')\n","  print('some text')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"WlL61dIC5kwO"},"source":["# AssertionError\n","\n","Instead of waiting for a program to crash midway, you can also start by making an assertion in Python. We assert that a certain condition is met. If this condition turns out to be **True**, the program can continue. If the condition turns out to be **False**, you can have the program throw an `AssertionError` exception.\n","\n","<img src=\"https://files.realpython.com/media/assert.f6d344f0c0b4.png\" alt=\"Drawing\" width=600/>\n"]},{"cell_type":"code","metadata":{"id":"hlWpVJeX5k0c","colab":{"base_uri":"https://localhost:8080/","height":178},"executionInfo":{"status":"error","timestamp":1597412826744,"user_tz":-240,"elapsed":1102,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"b261ee0e-9954-41a6-9860-3aa0416fa97d"},"source":["assert 1 == 2, \"This equality does not hold.\"\n","print(2+2)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"AssertionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-a85f9ed81189>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32massert\u001b[0m \u001b[0;36m1\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"This equality does not hold.\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mAssertionError\u001b[0m: This equality does not hold."]}]},{"cell_type":"markdown","metadata":{"id":"iSTTuDU25k4r"},"source":["# Handling Exceptions: try and except \n","\n","The `try` and `except` block in Python is used to catch and handle exceptions. Python executes code following the `try` statement as a \"normal\" part of the program. The code that follows the `except` statement is the program's response to any exceptions in the preceding `try` clause.\n","\n","<img src=\"https://files.realpython.com/media/try_except.c94eabed2c59.png\" alt=\"Drawing\" width=600/>\n"]},{"cell_type":"markdown","metadata":{"id":"SSmly1pg5k9F"},"source":["When syntactically correct code runs into an error, Python will throw an exception error. This exception error will crash the program if it is unhandled. The `except` clause determines how your program responds to exceptions."]},{"cell_type":"code","metadata":{"id":"qB5hL71w5lBo","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413112727,"user_tz":-240,"elapsed":979,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"1988f433-2bba-42cf-8f02-8effb6254f93"},"source":["x = 0\n","y = 5\n","try:\n","  z = y / x\n","  print('divided succesfully')\n","except:\n","  print('divided by zero')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["divided by zero\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"lzC833Op5lFW","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413119243,"user_tz":-240,"elapsed":1286,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"c2b64a9d-219c-4e5b-f1bd-d9e0677095f9"},"source":["x = 2\n","try:\n","    z = y / x\n","    print('divided succesfully')\n","except:\n","    print('divided by zero')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["divided succesfully\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"3EItW8z2qoaB"},"source":["The good thing here is that the program did not crash. \n","\n","In order to see exactly what went wrong, you would need to catch the error that the function threw.\n","\n","The following code is an example where you capture the AssertionError and output that message to screen:"]},{"cell_type":"code","metadata":{"id":"QwHm9Duz5_-r"},"source":["def divide(x, y):\n","  assert x != 0, 'Zero division is not allowed'\n","  return y / x"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Sj0z6ptg6ACu","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413236797,"user_tz":-240,"elapsed":1040,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"5f1f8cf6-587b-4d5d-ffb5-c5824521f07c"},"source":["x = 0\n","y = 5\n","try:\n","  z = divide(x, y)\n","  print('divided succesfully')\n","except ZeroDivisionError as e:\n","  print(e)\n","  # print('divided by zero')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Zero division is not allowed\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Fml90JdMP-i4","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413457071,"user_tz":-240,"elapsed":1004,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"2d96fab7-6594-4064-b28e-3027946b9f8f"},"source":["x = 0\n","y = 5\n","try:\n","  # z = divide(x, y)\n","  y / x\n","  print('divided succesfully')\n","except (ZeroDivisionError, AssertionError) as e:\n","  print(e)\n","  # print('divided by zero')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["division by zero\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"5Hk_1iR76AGy","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413266496,"user_tz":-240,"elapsed":1073,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"0bc9e7fc-8616-4299-97d6-58a77d1cd879"},"source":["d = {1:2, 'a':7}\n","\n","try:\n","  print(d['b'])\n","except KeyError:\n","  print('Some text')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Some text\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"PJSLldHB6AK1"},"source":["The first message is the `AssertionError`. When you executed the function, you caught the `AssertionError` exception and printed it to screen."]},{"cell_type":"code","metadata":{"id":"fCAKXBE36AOt","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413474403,"user_tz":-240,"elapsed":1489,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"e6d7189a-f425-4036-dc62-9e6a46938437"},"source":["try:\n","  5 / 0\n","  print('divided succesfully')\n","except ZeroDivisionError as error:\n","  print(error)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["division by zero\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"NU7kmtkz6ASL"},"source":["Catching Exception hides all errors, even those which are completely unexpected. This is why you should avoid bare `except` clauses in your Python programs. Instead, you'll want to refer to specific exception classes you want to catch and handle.\n","\n","* A `try` clause is executed up until the point where the first exception is encountered.\n","* Inside the `except` clause, or the exception handler, you determine how the program responds to the exception.\n","* You can anticipate multiple exceptions and differentiate how the program should respond to them.\n","* Avoid using bare except clauses."]},{"cell_type":"code","metadata":{"id":"fvkcQiGVqoeK","colab":{"base_uri":"https://localhost:8080/","height":229},"executionInfo":{"status":"error","timestamp":1597413484315,"user_tz":-240,"elapsed":1114,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"b02e0a05-36dd-4185-f1ea-8509a24154c0"},"source":["# Lets put another type of error in try clause\n","x = 0\n","try:\n","    y = x + 'a'\n","    print('divided succesfully')\n","except ZeroDivisionError:\n","    print('divided by zero')"],"execution_count":null,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-19-5cb2b0a3ec58>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m     \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'a'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'divided succesfully'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}]},{"cell_type":"code","metadata":{"id":"7OaHWSiR6Kp0","colab":{"base_uri":"https://localhost:8080/","height":50},"executionInfo":{"status":"ok","timestamp":1597413568719,"user_tz":-240,"elapsed":999,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"b47b1623-3a4a-47c2-f849-809667e81532"},"source":["# You can add multipe errors in the same except clause\n","#  or write separate except clause for type of error\n","\n","x = 1\n","try:\n","    y = 1 / x + 'a'\n","    print('divided succesfully')\n","except (ZeroDivisionError,TypeError) as e:\n","    print(e)    \n","    y = 1 / x\n","\n","print(y)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["division by zero\n","1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"_AIM6GCZ6KuB","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413556240,"user_tz":-240,"elapsed":1435,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"decb07c5-8924-4247-8484-963aa4fd10c8"},"source":["try:\n","    y = x + 'a'\n","    print('divided succesfully')\n","except ZeroDivisionError as f:\n","    print(f)\n","except TypeError as e:\n","    print(e)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["division by zero\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"uhvxsZoo6Kys","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413586932,"user_tz":-240,"elapsed":1051,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"b75a3fc1-cfd7-46ef-8685-f1ec1441482d"},"source":["try:\n","    y = 5 / 0 + 'a'\n","    print('divided succesfully')\n","except ZeroDivisionError:\n","    print('divided by zero')\n","except TypeError as e:\n","    print(e)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["divided by zero\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"5A2lyFWd6rW-","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1597413807090,"user_tz":-240,"elapsed":1142,"user":{"displayName":"Nshan Potikyan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GgwEEDvEOwXSKYbrUPj7UT4cqoOH73Ij4jb4412=s64","userId":"01488034774237415337"}},"outputId":"c5629c27-3f55-4cc7-8df4-bb9c479c82c8"},"source":["d = [1, 2, 3, 4]\n","try:\n","  d\n","except (ValueError, TypeError):\n","  print('a')\n","except IndexError:\n","  print('b')\n","except:\n","  print('something')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["a\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"7TAXC4IJ6K2u"},"source":["# the else clause\n","\n","In Python, using the else statement, you can instruct a program to execute a certain block of code only in the absence of exceptions.\n","\n","<img src=\"https://files.realpython.com/media/try_except_else.703aaeeb63d3.png\" alt=\"Drawing\" width=600/>\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"UW6xKqp26K6k"},"source":["try:\n","  z = divide(0, 6)\n","except AssertionError as error:\n","  print(error)\n","else:\n","  print('divided succesfully')"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"HRNWb1zI6K-r"},"source":["# finally clause\n","\n","Imagine that you always had to implement some sort of action to clean up after executing your code. Python enables you to do so using the finally clause.\n","\n","<img src=\"https://files.realpython.com/media/try_except_else_finally.a7fac6c36c55.png\" alt=\"Drawing\" width=600/>\n","\n"]},{"cell_type":"code","metadata":{"id":"R4RIh92X6LDx"},"source":["try:\n","  z = divide(5, 6)\n","except AssertionError as error:\n","  print(error)\n","else:\n","  print('divided succesfully')\n","finally:\n","  print('This will always appear')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"4ndGlaxU6W9l"},"source":["try:\n","  z = divide(0, 6)\n","except AssertionError as error:\n","  print(error)\n","else:\n","  print('divided succesfully')\n","finally:\n","  print('This will always appear')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"WN_05c3D6XCX"},"source":["d['b']"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"NnO6nBgT6XGc"},"source":["d = {1: '2', '2': 9}\n","try:\n","  d['b']\n","  # d + 5\n","except KeyError as x:\n","  print(x)\n","  print(d.get('b', 'Hello'))\n","else:\n","  print('divided succesfully')\n","finally:\n","  # print(5/0)\n","  print(5)\n","  # print('This will always appear')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"-w-gvV5K6XK0"},"source":["d = {1: '2', '2': 9}\n","try:\n","  print(d['2'] + d[1])\n","except KeyError as x:\n","  print(x)\n","  print(d.get('b', 'Hello'))\n","else:\n","  print('divided succesfully')\n","finally:\n","  print('This will always appear')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"bm3JlxzZ6XOr"},"source":["d = {1: '2', '2': 9}\n","try:\n","  if type(d['2']) != 'str':\n","    raise Exception('string object')\n","except KeyError as x:\n","  print(x)\n","  print(d.get('b', 'Hello'))\n","else:\n","  print('divided succesfully')\n","finally:\n","  print('This will always appear')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"WcTbUOKs6de1"},"source":["x = -1\n","assert x > 0, 'x is not positive'"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"eRB6m8rG6djh"},"source":["In the previous code, everything in the `finally` clause will be executed. It does not matter if you encounter an exception somewhere in the `try` or `else` clauses.\n","\n","To sum up:\n","* `raise` allows you to throw an exception at any time.\n","* `assert` enables you to verify if a certain condition is met and throw an exception if it isn't.\n","* In the `try` clause, all statements are executed until an exception is encountered.\n","* `except` is used to catch and handle the exception(s) that are encountered in the `try` clause.\n","* `else` lets you code sections that should run only when no exceptions are encountered in the `try` clause.\n","* `finally` enables you to execute sections of code that should always run, with or without any previously encountered exceptions."]}]}